//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livraria.Sistema.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class EDITORAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EDITORAS()
        {
            this.LIVROS = new HashSet<LIVROS>();
        }
    
        public int IDEDITORA { get; set; }
        [Required(ErrorMessage = "Campo obrigatório.")]
        [StringLength(14, MinimumLength = 14, ErrorMessage = "Este campo deve possuir 14 números.")]
        public string CNPJ { get; set; }
        [Required(ErrorMessage = "Campo obrigatório.")]
        [StringLength(150, MinimumLength = 2, ErrorMessage = "Nome inválido.")]
        public string NOMEFANTASIA { get; set; }
        [DataType(DataType.EmailAddress)]
        public string EMAIL { get; set; }
        public string TELEFONE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIVROS> LIVROS { get; set; }
    }
}
