//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livraria.Sistema.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class FUNCIONARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUNCIONARIOS()
        {
            this.MOVIMENTACAO = new HashSet<MOVIMENTACAO>();
        }
    
        public int IDFUNCIONARIOS { get; set; }
        [Required(ErrorMessage = "Campo obrigatório.")]
        [StringLength(200, MinimumLength = 1, ErrorMessage = "Nome inválido.")]
        public string NOME { get; set; }
        public string CELULAR { get; set; }
        [Required(ErrorMessage = "Campo obrigatório.")]
        [DataType(DataType.EmailAddress)]
        public string EMAIL { get; set; }
        [Required(ErrorMessage = "Campo obrigatório.")]
        [DataType(DataType.Password)]
        public string SENHA { get; set; }
        [Required(ErrorMessage="Campo obrigatório.")]
        [StringLength(200, MinimumLength = 1, ErrorMessage = "Username inválido.")]
        public string USERNAME { get; set; }
        public string LoginErrorMessage { get; internal set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIMENTACAO> MOVIMENTACAO { get; set; }
        
    }
}
