//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livraria.Sistema.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDLIVRARIAEntities : DbContext
    {
        public BDLIVRARIAEntities()
            : base("name=BDLIVRARIAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORIAS> CATEGORIAS { get; set; }
        public virtual DbSet<DISTRIBUIDORAS> DISTRIBUIDORAS { get; set; }
        public virtual DbSet<EDITORAS> EDITORAS { get; set; }
        public virtual DbSet<FUNCIONARIOS> FUNCIONARIOS { get; set; }
        public virtual DbSet<LIVROS> LIVROS { get; set; }
        public virtual DbSet<MOVIMENTACAO> MOVIMENTACAO { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
