//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livraria.Sistema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIVROS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIVROS()
        {
            this.MOVIMENTACAO = new HashSet<MOVIMENTACAO>();
            this.CATEGORIAS = new HashSet<CATEGORIAS>();
            this.DISTRIBUIDORAS = new HashSet<DISTRIBUIDORAS>();
        }
    
        public int IDLIVRO { get; set; }
        public string EAN13 { get; set; }
        public string ISBN { get; set; }
        public string TITULO { get; set; }
        public string AUTOR { get; set; }
        public Nullable<byte> EDICAO { get; set; }
        public string ANOEDICAO { get; set; }
        public string FORMATO { get; set; }
        public short NUMEROPAGINAS { get; set; }
        public string ORIGEM { get; set; }
        public decimal PRECO { get; set; }
        public int IDMOVIMENTACAO { get; set; }
        public int IDEDITORA { get; set; }
    
        public virtual EDITORAS EDITORAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIMENTACAO> MOVIMENTACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATEGORIAS> CATEGORIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISTRIBUIDORAS> DISTRIBUIDORAS { get; set; }
    }
}
