//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livraria.Sistema.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class MOVIMENTACAO
    {
        public int IDMOVIMENTACAO { get; set; }
        [Required(ErrorMessage = "Campo obrigatório.")]
        [Range(1, 300, ErrorMessage = "Número inválido")]
        public short QUANTIDADEPRODUTO { get; set; }
        [Required(ErrorMessage = "Campo obrigatório.")]
        public string OPERACAO { get; set; }
        [Required(ErrorMessage = "Campo obrigatório.")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime DATA { get; set; }
        [Required(ErrorMessage = "Campo obrigatório.")]
        public int IDDISTRIBUIDORA { get; set; }
        [Required(ErrorMessage = "Campo obrigatório.")]
        public int IDLIVRO { get; set; }
        [Required(ErrorMessage = "Campo obrigatório.")]
        public int IDFUNCIONARIO { get; set; }
    
        public virtual DISTRIBUIDORAS DISTRIBUIDORAS { get; set; }
        public virtual FUNCIONARIOS FUNCIONARIOS { get; set; }
        public virtual LIVROS LIVROS { get; set; }
    }
}
